name: Build Examples

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  examples:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: yarn prepublish

      - name: Build examples
        run: yarn build-examples

      - name: Test built examples
        run: yarn test-ci
        env:
          # Workaround for https://github.com/facebook/jest/issues/8536 
          TEMP: ${{ runner.temp }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint-ci
